import React from 'react';
import Header from './Header';
import Footer from './Footer';

const OfertaPageEN = ({ onOpenModal }) => {
  return (
    <div className="app-container">
      <Header onOpenModal={onOpenModal} />
      <main style={{ paddingTop: '120px', paddingBottom: '40px', minHeight: 'calc(100vh - 200px)', backgroundColor: 'white' }}>
        <div className="container" style={{ maxWidth: '900px', margin: '0 auto', textAlign: 'left', color: 'var(--text-main)', padding: '0 1.5rem' }}>
          <h1 style={{ fontSize: '1.75rem', fontWeight: '800', marginBottom: '2rem', textTransform: 'uppercase' }}>
            PUBLIC OFFER
          </h1>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', lineHeight: '1.6', fontSize: '0.95rem', color: 'var(--text-muted)' }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: '700', marginTop: '1rem', color: 'var(--text-main)' }}>1. General Provisions. Subject of the Agreement</h3>
            <p>1.1. This document constitutes a written offer (Offer) of "BusinessFirst" LLP (BIN - 250740000431, hereinafter referred to as the "Organizer"), addressed in accordance with part 1 of Article 395 of the Civil Code of the Republic of Kazakhstan to any Participant wishing to purchase Tickets to the Organizer's Events through the Ticket Sales System on the Organizer's Website for the purpose of attending the Event, by accepting the Offer by the Participant in the prescribed manner (part 3 of Article 396 of the Civil Code of the Republic of Kazakhstan), which is considered to be compliance with the written form of the Agreement (part 2 of Article 394 of the Civil Code of the Republic of Kazakhstan). This Offer contains all essential terms of the agreement.</p>
            <p>1.2. This Offer regulates the conditions for purchasing Tickets to the Organizer's Events, conditions for attending the Organizer's Events, and the rights and obligations arising in connection with this for the Organizer and the Participant. Before purchasing Tickets through the Ticket Sales System on the Organizer's Website, the Participant must familiarize themselves with the terms of this Offer. If the Participant does not fully accept the terms of this Offer, the Participant must not purchase Tickets to the Events through the Ticket Sales System on the Organizer's Website. The purchase of Tickets through the Ticket Sales System on the Organizer's Website means that the Participant has familiarized themselves and fully agrees with the terms of this Offer.</p>
            <p><strong>1.3. Terms and Definitions</strong></p>
            <p>1.3.1. In this Agreement, unless the context clearly indicates otherwise, the following words and expressions used when the Parties interact during the performance of obligations shall have the meanings set out below:</p>
            <p>1.3.1.1. Event – The type of event (conference/concert) Event – International exhibition of green technologies and sustainable solutions "RES 2027 EXPO", organized and conducted by the Organizer, for the purpose of attending which the Participant purchases a Ticket via the Ticket Sales System. Date of the Event: May 5-7, 2027. Venue of the Event: Astana, 53/1 Mangilik El Avenue.</p>
            <p>1.3.1.2. Organizer – "BusinessFirst" LLP BIN- 250740000431, providing services for holding the Event, the attendance of which is carried out upon presentation of Tickets under the conditions determined by the Organizer in this Offer, the Rules of the Event, and the Event Program posted on the Organizer's Website. The Organizer ensures the operation of the Ticket Sales System and processes the information contained in the databases of the Ticket Sales System in accordance with the Law of the Republic of Kazakhstan dated May 21, 2013 No. 94-V "On Personal Data and their Protection".</p>
            <p>1.3.1.3. Participant – an individual with full legal capacity, who has familiarized themselves with the terms of this Offer and accepted this Offer, purchasing a Ticket/Tickets through the Ticket Sales System on the Organizer's Website.</p>
            <p>1.3.1.4. Parties — a joint reference to the Organizer and the Participant.</p>
            <p>1.3.1.5. Organizer's Website – a website on the Internet information and telecommunication network, located at <a href="https://res2027expo.kz/" style={{color: 'var(--bg-dark-green)', textDecoration: 'underline'}}>https://res2027expo.kz/</a>, intended for the presentation of the Event and the realization (sale) of Tickets for the Event, providing information to potential visitors of the Event and Customers about the Organizer's Event, and the possibility of purchasing Tickets on the Organizer's Website through the Ticket Sales System.</p>
            <p>1.3.1.6. User – any visitor to the Organizer's Website.</p>
            <p>1.3.1.7. Acceptance of the Offer — full and unconditional acceptance of the Offer by the Participant performing the actions specified in this Offer.</p>
            <p>1.3.1.8. Ticket Sales System – an automated Ticket Sales System via the Organizer's Website.</p>
            <p>1.3.1.9. Ticket – a document sold to the Participant by the Organizer using the Ticket Sales System, certifying the conclusion of an agreement between the Event Organizer and the Participant, granting the Participant the right to attend the Organizer's Event specified in the Ticket, under the conditions set out in the Event Rules and the Event Program posted on the Organizer's Website.</p>
            <p>1.3.1.10. Electronic Ticket – an electronic entrance document generated via the online ordering section on the Organizer's Website, which, when scanned by special equipment, confirms the Participant's right to attend the Event and receive the Organizer's services specified in the "electronic" Ticket, as well as in the Event Rules and Event Program posted on the Organizer's Website.</p>
            <p>1.3.1.11. Face Value of the Ticket – the price of attending the Event established by the Event Organizer. Information on the face value of the Ticket is posted on the Organizer's Website. The Ticket price is calculated in Kazakhstani tenge.</p>
            <p>1.3.1.12. Order – one or more Tickets for the Event selected by the Participant from the Ticket Sales System on the Organizer's Website. The total cost of the Order includes the face value of the Tickets selected by the Participant.</p>
            <p>1.3.1.13. Participant's Registration on the Organizer's Website – the Participant's entry into the Ticket Sales System on the Organizer's Website of their registration data: surname, first name, patronymic; gender, contact phone number, email address, as well as consent to the terms of this Offer, the terms of the Privacy Policy, and Consent to the processing of personal data by ticking the appropriate box during registration on the Organization's Website.</p>
            <p>1.3.1.14. Participant's Email Address – the email address provided by the Participant during registration on the Organizer's Website.</p>
            <p>1.3.1.15. CC RK - Civil Code of the Republic of Kazakhstan.<br/>In this document, the above definitions are used equally in the singular and plural in the following meanings.<br/>The Offer may use terms not defined in this section. In this case, the interpretation of such a term is made in accordance with the text of the Offer. In the absence of an unambiguous interpretation of the term in the text of the Offer, one should be guided by the interpretation of the term determined by the legislation of the Republic of Kazakhstan.</p>
            <p>1.4. The subject of this Offer is the provision to the Participant of services for processing and selling Ticket/Tickets to the Organizer's Events using the Ticket Sales System on the Organizer's Website, providing services for holding the Event for the purpose of the Participant's attendance of the Event on the basis of a purchased Ticket under the terms of this Offer.</p>
            <p>1.5. The purchase of Tickets by the Participant using the Ticket Sales System is carried out under the terms of this Offer exclusively for personal use, precluding the resale or transfer of Tickets to a third party for commercial purposes.</p>
            <p>1.6. The Offer comes into force from the date specified in the "Effective Date" section. The Offer is considered sent from the moment of its publication on the Organizer's Website at: <a href="https://res2027expo.kz/" style={{color: 'var(--bg-dark-green)', textDecoration: 'underline'}}>https://res2027expo.kz/</a>, and is valid for the entire period this Offer is posted at the specified address.</p>
            <p>1.7. In accordance with part 5 of Article 395 of the CC RK, upon acceptance of the conditions set out below, the individual making the acceptance of the Offer becomes a Participant (in accordance with part 3 of Article 396 of the CC RK, acceptance of the Offer is equivalent to concluding a contract on the terms set out in the Offer).</p>
            <p>1.8. The acceptance of this Offer by the Participant is carried out by the Participant consistently performing the following actions:<br/>
              1.8.1. Registration on the Organizer's Website on the terms posted on the Organizer's Website;<br/>
              1.8.2. Consent of the Participant to the terms of this Offer by electronically ticking the "I agree and accept the terms of the Offer" box on the Organizer's Website;<br/>
              1.8.3. Consent of the Participant to the terms of the Privacy Policy by electronically ticking the "I agree and accept the terms of the Privacy Policy" box on the Organizer's Website;<br/>
              1.8.4. Selection of the desired participation format in the Ticket Sales System on the Organizer's Website;<br/>
              1.8.5. Placing an Order to purchase a Ticket in the Ticket Sales System on the Organizer's Website;<br/>
              1.8.6. Payment by the Participant of the Ticket Purchase Order on the Organizer's Website in full (in the amount of the face value of the Ticket/Tickets).
            </p>
            <p>1.9. The completion of all actions specified in clause 1.8. of the Offer, including the full one-time payment by the Participant of the face value of the Ticket/Tickets, signifies full and unconditional acceptance by the Participant of all terms of the Offer, Privacy Policy, and is recognized by the Parties as an analogue of the Participant's handwritten signature, i.e., the Participant's consent to conclude an Agreement with the Organizer on the terms of this Offer. The Offer and the Privacy Policy are always posted on the Organizer's Website. The Organizer has the right to unilaterally amend this Offer, but in any case, such changes are published in a timely manner and are publicly available on the Website. The use of the Organizer's services by the Participant after amendments to the text of the Offer means acceptance of the Offer taking into account the amendments made without any exceptions or restrictions.</p>
            <p>1.10. The Participant, accepting the Offer:<br/>
              a) has fully read the terms of this Offer;<br/>
              b) fully understands the subject of this Offer (Agreement);<br/>
              c) has familiarized themselves with the terms of this Offer and fully understands the meaning and consequences of their actions regarding the conclusion and execution of the Agreement;<br/>
              d) undertakes to provide reliable and complete information when using the Organizer's Website, when placing an Order and paying for it;<br/>
              e) undertakes to independently verify the Order details immediately before placing it, and the Ticket details immediately upon receiving it. The Participant bears full responsibility for the accuracy and legality of the use of the data provided during checkout.
            </p>
            <p>1.11. Procedure for processing personal data of Users/Participants.<br/>
              1.11.1. By accepting the terms of this Offer, the Participant, acting freely, of their own free will and in their own interest, expresses to the Organizer their specific, conscious, and informed consent to the processing of personal data provided during registration on the Organizer's Website and when purchasing a Ticket to the Organizer's Event and defined in this Offer.<br/>
              1.11.2. The Participant, in accordance with the Law of the Republic of Kazakhstan "On Personal Data and their Protection", gives their consent to the processing by the Organizer (including obtaining from the Participant and/or any third parties) of personal data: surname, first name, patronymic, personal phone numbers, contact information, and any other information relating to their identity, available or known at any specific moment in time to the Organizer, and confirms that, by giving such consent, they act of their own free will and in their own interests.<br/>
              1.11.3. Personal data processing means recording, systematization, accumulation, storage, clarification (update, modification), extraction, use, transfer (distribution, provision, access), including cross-border, depersonalization, blocking, deletion, and destruction of personal data that do not fall under special categories for which, according to the current legislation of the Republic of Kazakhstan, the written consent of the Participant is required.<br/>
              1.11.4. The purpose of personal data processing is the performance by the Organizer of its obligations to the Participants, as well as the holding of necessary marketing events.<br/>
              1.11.5. The transfer of personal data to third parties is carried out in accordance with the current legislation of the Republic of Kazakhstan and agreements between the Parties.<br/>
              1.11.6. The consent to personal data processing by the Organizer may be revoked by the Participant by sending a written request to the Organizer's representative at the email address: office@res2026expo.kz.<br/>
              1.11.7. The Participant confirms that the email address provided when issuing the Ticket is public information.
            </p>
            <p>1.12. By concluding this Agreement, the Participant understands the meaning of their actions and is capable of managing them, and is not under the influence of delusion, deception, violence, or threat. The Agreement is concluded by the participant voluntarily, with a preliminary complete review of the terms of this public offer Agreement, the contents of which the Participant understands. If the Participant did not have the appropriate authority at the time of acceptance of the public offer on behalf of a legal entity, then they, as an individual, assume full responsibility for the execution of this public offer.</p>

            <h3 style={{ fontSize: '1.1rem', fontWeight: '700', marginTop: '1rem', color: 'var(--text-main)' }}>2. Procedure for Purchasing Tickets to the Organizer's Event</h3>
            <p>2.1. The Participant is obliged to familiarize themselves with the conditions of the Event for which they intend to purchase Tickets. The Participant acknowledges that, by purchasing Tickets, they are familiar with the information and conditions of the Event, and agree to purchase these Tickets under such conditions.<br/>
              2.2. The Participant has the right to purchase an Event Ticket using cashless payment at the prices listed on the Event Website. The Participant has the right to make the Order payment by any of the methods offered by the Organizer, information about which is available on the Organizer's Website.<br/>
              2.3. When making a payment by bank card, the Participant must use a bank card issued in the Participant's name. Payment is not accepted if the Participant violates the payment terms established by this Offer and the legislation of the Republic of Kazakhstan.<br/>
              2.4. Under the terms specified in this Offer, after the Organizer receives payment, the Tickets are considered purchased, which is confirmed by an Electronic Ticket provided by the Organizer to the Participant online on the Organizer's Website, in accordance with the terms posted on the Organizer's Website.<br/>
              2.5. The Electronic Ticket confirms the Participant's right to attend the Event and receive the Organizer's services to the extent defined in the Electronic Ticket, as well as in the Privacy Policy, Event Rules, and Event Program posted on the Event Website.<br/>
              2.6. The Organization is not responsible for the Organizer's Event not meeting the Participant's expectations and/or their subjective assessment.<br/>
              2.7. The Organizer has the right to make changes to the Event Program by notifying the Participant by posting updated information on the Organizer's Website in the Event information section, including the replacement of speakers. All changes become effective immediately upon their posting on the Organizer's Website and are deemed communicated to the Participant from the moment of such publication. The use by the User or Participant of the Organizer's Website for the purpose of placing an Order, for other purposes after making changes to the Offer, Event Program, or other changes to information posted on the Organizer's Website implies the User's, Participant's consent to the changes made.<br/>
              2.8. The Organizer has the right to unilaterally change the format of the Event, replacing the offline format of the Event (with the physical presence of Event visitors at the venue) with the online format of the Event, due to the need for the Organizer to take measures to prevent the spread of a new coronavirus infection under a state of high alert. The Organizer must notify the Participant about the change in the Event format by posting this information on the Organizer's Website.<br/>
              2.9. The Organizer has the right to refuse the User the processing of a Ticket Order without giving reasons. If the Ticket was paid for by the Participant, the Organizer undertakes to either send the Participant an order confirmation and an Electronic Ticket, or to cancel the Order/Ticket sale and refund the funds paid by the Participant when purchasing the Ticket. No damages are subject to reimbursement by the Organizer to the Participant/User in this case.
            </p>

            <h3 style={{ fontSize: '1.1rem', fontWeight: '700', marginTop: '1rem', color: 'var(--text-main)' }}>3. Exchange, Refund of Tickets for the Organizer's Event</h3>
            <p>3.1. Purchased tickets are non-refundable if the Organizer's Website states "Tickets are non-refundable".<br/>
              3.2. To state their intention to refuse to perform this Agreement, the Participant must notify the Organizer in writing 10 (Ten) calendar days before the start of the Event via the email address: office@res2026expo.kz, specifying the email address used during the Ticket purchase, the order number, and the date.<br/>
              3.3. The day of the Participant's appeal is the day the relevant application is received by the Organizer.<br/>
              3.4. Refund of funds for purchased Tickets in case of cancellation, replacement, or postponement of the Event is carried out by the Organizer provided an official letter from the Organizer regarding the cancellation, replacement, or postponement of the Event is received. Only Tickets purchased on the Website: <a href="https://res2027expo.kz/" style={{color: 'var(--bg-dark-green)', textDecoration: 'underline'}}>https://res2027expo.kz/</a> are accepted for refund.<br/>
              3.5. Refund of funds for purchased Tickets is not carried out in the event of a violation of the deadline specified in clause 3.2. of this Agreement.<br/>
              3.6. Tickets sold by the Organizer within special programs and promotions providing for special conditions for ticket purchases (including benefits, discounts, promo codes), at the discretion of the Organizer, may not be accepted for a refund.<br/>
              3.7. In the case of a refund, the Organizer undertakes to transfer the funds within 15 (Fifteen) working days from the moment of Ticket cancellation to the details from which the payment for the Tickets was made, and in a manner similar to that used for paying for the canceled Ticket. The Participant bears sole responsibility for the impossibility of refunding funds to the Participant's details from which payment was made.<br/>
              3.8. The Organizer does not refund the Participant for unused or lost Tickets.
            </p>

            <h3 style={{ fontSize: '1.1rem', fontWeight: '700', marginTop: '1rem', color: 'var(--text-main)' }}>4. Liability</h3>
            <p>4.1. The Parties shall not be liable if the non-performance or improper performance of the terms of the Offer is caused by force majeure circumstances that arose against the will and desire of the parties and which they could not prevent, avoid, or foresee (force majeure).<br/>
              4.1.1. If at the time of the face-to-face events there is a decision of the state authorities and (or) the state authority of Almaty city to cancel any events due to the spread of the COVID-19 coronavirus infection, the parties have the right to make a decision (without mutual claims) to terminate the Agreement and refuse to fulfill their obligations under this Agreement, without applying any penalties.<br/>
              4.1.2. In the event of the circumstances specified in clause 4.1.1. of this Agreement, the Organizer notifies the Participant and offers to replace the service with participation in the same Event online. If the Participant agrees, a link for access to the online broadcast of the Event is sent to them.<br/>
              4.1.3. If at the time of the face-to-face Events there is a decision by state authorities and (or) the state authority of Almaty city regarding the need to present a special QR code in public places to prevent the spread of coronavirus infection, only participants with QR codes will be admitted to the conference.<br/>
              4.2. The Organizer is not responsible and does not compensate the Participant for any damages (including direct and indirect damages) for failures, interruptions in the Ticket Sales System software on the Organizer's Website that are beyond the Organizer's control, resulting from or in connection with the actions and (or) omissions of third parties providing communication, energy supply services, including if the latter is not under the direct control of the Organizer.<br/>
              The Organizer is not responsible for the inability to provide services by the Organizer / accept services by the Participant if such impossibility occurred due to disruptions in the Internet network, software, or Participant's equipment.<br/>
              The Organizer has the right to close access to the Event Website without prior notification to the User/Participant and is not responsible for temporary or permanent termination of access to it for reasons beyond the Organizer's control. The Organizer is not responsible for direct and/or indirect damages resulting from the use or inability to use the Event Website and unauthorized access to it.<br/>
              4.3. The Participant bears full responsibility under the current legislation of the Republic of Kazakhstan for the consequences arising from the provision of inaccurate or deliberately false information, and bears responsibility for violating the rights and interests of other persons as a result of such actions.<br/>
              4.4. The Participant bears full responsibility under the current legislation of the Republic of Kazakhstan for illegal actions with bank cards or other payment means aimed at placing an Order and paying for it.<br/>
              4.5. The Participant assumes full responsibility and risks associated with placing Orders, concluding and executing the Agreement with the Organizer. The Participant bears sole responsibility for any problem that arises during the registration, placement, confirmation, and payment of the Order when purchasing a Ticket. In such a case, the Organizer is not liable for any damage (monetary or otherwise) resulting from a problem caused by or attributable to the error or negligence of the Participant when using the Organizer's Website, including the unsuccessful completion or confirmation of any transaction.<br/>
              4.6. Disputes arising during the execution of an agreement concluded on the terms of this Offer are resolved through a claim procedure. The claim must be sent to the Organizer in writing to the Organizer's address, accompanied by documents substantiating the claims. The received claim is considered by the Organizer within 30 (thirty) calendar days from the date of its receipt. If disputes and disagreements between the Parties cannot be settled through negotiations, they are subject to resolution in court at the Organizer's location.<br/>
              4.7. In any case, the amount of the Organizer's liability for damages due to non-performance/improper performance of this Offer cannot exceed the price of the Ticket purchased by the Participant. To the maximum extent permitted by applicable law, and notwithstanding any other provisions of this Offer, the total liability of the Organizer to the Participant or any individual or legal entity bringing claims through the Participant, as a result of relations with the Participant or on the latter's instruction, concerning any grounds for filing a lawsuit, claims, damages, demands, liability, losses, and proceedings of any type and nature, including all legal costs, court fees, and expenses on representatives' services arising from or related in any way to this Offer, regardless of the cause or causes, including, but not limited to, any breaches of the Agreement, costs of correcting defects, negligence, or strict liability shall not exceed the cost of the Ticket purchased by the Participant.<br/>
              4.8. In the event of a breach by the Participant of any of the Participant's obligations provided for in the Offer, the Organizer has the right to refuse to fulfill the Offer and terminate the Agreement unilaterally and out of court.<br/>
              4.9. In all other matters not provided for by this Offer, the Parties will be guided by the current legislation of the Republic of Kazakhstan.
            </p>

            <h3 style={{ fontSize: '1.1rem', fontWeight: '700', marginTop: '1rem', color: 'var(--text-main)' }}>5. Special Conditions</h3>
            <p>5.1. Information provided to the Participant during the Event is the intellectual property of the Organizer and other copyright holders and is subject to protection under the legislation of the Republic of Kazakhstan. Distribution of information obtained at the Events for commercial purposes is unacceptable.<br/>
              5.2. With respect to any monetary obligations of the Parties under the Agreement, the legal interest provided for in Article 353 of the Civil Code of the Republic of Kazakhstan (interest on the debt amount for the period of use of funds) is not charged and is not paid by the Parties.<br/>
              5.3. All suggestions, questions, and notices regarding this Offer should be communicated to the Organizer at the email address: office@res2026expo.kz, or at the Organizer's address specified in this Offer.<br/>
              5.4. If any provision of the Offer is or becomes invalid due to conflict or changes in the current legislation of the Republic of Kazakhstan, this is not a basis for suspending the validity of the remaining provisions of the Offer.<br/>
              5.5. The Parties do not have the right to fully or partially assign their rights under the Agreement without the prior written consent of the other Party.<br/>
              5.6. The Agreement is the final agreement between the Parties regarding the subject matter and content of the Agreement. From the moment of Acceptance, all previous arrangements, agreements, understandings, and decisions of the Parties lose their force.<br/>
              In accordance with paragraph 1 of Article 385 of the Civil Code of the Republic of Kazakhstan, an offer is a proposal to conclude a contract made to one or more specific persons if it is sufficiently definite and expresses the intention of the person making the proposal to consider themselves bound in the event of its acceptance (accept). A proposal is sufficiently definite if it specifies the essential terms of the contract or the procedure for determining them.<br/>
              According to paragraph 4 of Article 395 of the Civil Code of the Republic of Kazakhstan, advertisements and other proposals addressed to an undefined circle of persons are considered an invitation to make offers unless otherwise expressly stated in the proposal.<br/>
              Based on paragraph 5 of Article 395 of the Civil Code of the Republic of Kazakhstan, a proposal containing all the essential terms of the contract, which reveals the will of the person making the proposal to conclude a contract on the terms specified in the proposal with anyone who responds, is recognized as an offer (public offer).<br/>
              The text of this Agreement is a public offer in accordance with paragraph 1 of Article 385 of the Civil Code of the Republic of Kazakhstan.
            </p>

            <div style={{ marginTop: '2rem', padding: '1.5rem', backgroundColor: '#f8f9fa', borderRadius: '8px' }}>
              <strong>Information about the Organizer:</strong><br/>
              Name of legal entity: "BusinessFirst" LLP<br/>
              Legal address: Kazakhstan, Astana city, Saryarka district, Samal Microdistrict, building 12, postal code 010000<br/>
              BIN : 250740000431<br/>
              Account : KZ288562203150233653<br/>
              BIC : KCJBKZKX<br/>
              Bank Name : JSC "Bank CenterCredit"
            </div>
          </div>
        </div>
      </main>
      <Footer onOpenModal={onOpenModal} />
    </div>
  );
};

export default OfertaPageEN;
